In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch 
import chofer_torchex.nn

In [17]:
ms = torch.tensor([[0, 2.0], [0, 2.0]])
batch = [ms, ms.repeat(2, 1), torch.tensor([], dtype=torch.float32)]
centers_init = torch.tensor([[0, 2.0], [1,1], [5, 10]])

In [30]:
sl_rat_hat = chofer_torchex.nn.SLayerRationalHat(3, 
                                                 centers_init=centers_init)

sl_rat = chofer_torchex.nn.SLayerRational(3, 
                                          centers_init=centers_init)

sl_exp = chofer_torchex.nn.SLayerExponential(3, 
                                          centers_init=centers_init, 
                                          sharpness_init=torch.ones(3, 2)*0.1)

layers = [sl_exp, sl_rat, sl_rat_hat]

In [31]:
batch = [x.to('cuda') for x in batch]
layers = [x.to('cuda') for x in layers]

In [32]:
layers[0].to('cuda')

SLayerExponential (... -> 3 )

In [33]:
layers

[SLayerExponential (... -> 3 ),
 SLayerRational (... -> 3 ),
 SLayerRationalHat (... -> 3 )]

In [34]:
for l in layers:
    print(l(batch))

tensor([[2.0000, 1.9604, 0.8213],
        [4.0000, 3.9208, 1.6426],
        [0.0000, 0.0000, 0.0000]],
       device='cuda:0', grad_fn=<SqueezeBackward0>)
tensor([[2.0000, 0.6667, 0.1429],
        [4.0000, 1.3333, 0.2857],
        [0.0000, 0.0000, 0.0000]], device='cuda:0', grad_fn=<SumBackward1>)
tensor([[ 1.0000, -0.3333, -0.0110],
        [ 2.0000, -0.6667, -0.0220],
        [ 0.0000,  0.0000,  0.0000]], device='cuda:0', grad_fn=<SumBackward1>)


In [35]:
sl_rat(batch).sum().backward()

In [ ]:
torch.autograd.Variable(torch.ones(2,2))

In [25]:
x = torch.rand(5)

In [28]:
x.device

device(type='cpu')

In [14]:
torch.LongTensor(range(5), device='cuda').device

device(type='cpu')